language: node_js
node_js:
  - 16
cache: npm
install:
  - npm install
script:
  - npm run test:coveralls
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
